version: '3'

services:

  cassandra:
    image: bitnami/cassandra:latest
    ports: 
      - 9042:9042
    volumes:
      - ./docker/volumes/cassandra:/bitnami

  couchbase:
    image: couchbase:community-6.6.0
    ports: 
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - ./docker/volumes/couchbase:/opt/couchbase/var
